### ISSUE TITLE
Startup() fails on TPM Simulator when built with wolfSSL

### ISSUE THREAD

**Issue by gpdloader** [microsoft/ms-tpm-20-ref#26]
In `Implementation.h
`

line : 
` #define AES_MAX_KEY_SIZE            ((AES_MAX_KEY_SIZE_BITS + 7) / 8)`

should be: 
 `#define AES_MAX_KEY_SIZE            AES_MAX_KEY_SIZE_BITS
`

Otherwise it doesn't work with wolfcrypt. I tried to fix locally. and seems to work.

**Comment by dvescovi1** [comment]
having similar build issues. Seems all to be related to defines in this file.

**Comment by DavidWooten** [comment]
Convention is that alg_MAX_KEY_SIZE is in bytes. Besides, there is no reason to define AES_MAX_KEY_SIZE to be AES_MAX_KEY_SIZE_BITS when there already is a definition for the maximum number of bits in the key.

**Comment by amarochk** [comment]
This definition cannot be the reason of the failure you see because it is absolutely correct syntactically, and the suggested replacement is logically wrong, as it assigns the number of bits to the number of bytes without proper conversion.

**Comment by dvescovi1** [comment]
In my case the error was introduced with the recent commits. It seems to work for the core code but it broke the sample TPM code. I am building for ARM64. The sample folder should also be renamed as it should support both ARM32 and ARM64 builds.

**Comment by dmcilvaney** [comment]
I'll take some time today or tomorrow and update our Implemenatation.h in the ARM32 sample. I'll leave the name for now since we are considering consolidating the fTPM TA with some other TAs in a central location. I would rather not break the build infrastructure twice in quick succession for that.

If you want to get back to building quickly 65b65354c6cce3212d9c512ec3ae2e23fe37c94d is a solid version.

**Comment by dvescovi1** [comment]
That would be great. 

I am using the previous commit for my build now.

 

Thanks,

David Vescovi, MVP

**Comment by dmcilvaney** [comment]
Having looked into it a bit more, I think its probably better to just leave the current version alone for a while.

I have a bunch of cleanup work comming for the TPM, and a new UEFI variable store TA. The UEFI repos include a pre-compiled version of the TPM which I think should be ok for now. The build instructions will be updated to reflect this for now (See https://github.com/ms-iot/imx-iotcore/pull/41).

If there is a need for an update in the short term let me know, I can spend the time bringing this version forward.

**Comment by gpdloader** [comment]
EDIT: i changed the issue title.

**Comment by dmcilvaney** [comment]
As a follow up, the new version is available at www.github.com/Microsoft/MSRSec. That repo includes ms-tpm-20-ref as a submodule. When I have some time I'll see about updating the sample here.

**Comment by DavidWooten** [comment]
A problem with a specific crypto library should not be fixed in Implementation.h (now  TpmAlgorithmDefines.h and TpmProfile.h). Those files are 'auto-generated' by a script that is run every time there is a new version of the spec. If you manually change an 'auto-generated' file in order to handle a specific crypto library then the script will change it back and it won't get caught unless it is tested with your favorite library. Things that are specific to a crypto library should go in a library-specific header, not in an auto-generated file.
