### ISSUE TITLE
TPM2_LoadExternal does not validate authPolicy size if private area is not loaded.

### ISSUE THREAD

**Issue by granaghan** [microsoft/ms-tpm-20-ref#71]
[TPM2_LoadExternal](https://github.com/microsoft/ms-tpm-20-ref/blob/b8e599267381badbe0571f8ace55b28a5f16457c/TPMCmd/tpm/src/command/Object/LoadExternal.c#L86) explicitly checked the authPolicy size in [1.16](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.16-code.pdf) and this was dropped in [1.38](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38-code.pdf). I have not been able to find an errata relating to it.
[PublicAttributesValidation](https://github.com/microsoft/ms-tpm-20-ref/blob/b8e599267381badbe0571f8ace55b28a5f16457c/TPMCmd/tpm/src/command/Object/Object_spt.c#L618) checks this, but is only called is the private area is loaded [here](https://github.com/microsoft/ms-tpm-20-ref/blob/b8e599267381badbe0571f8ace55b28a5f16457c/TPMCmd/tpm/src/subsystem/Object.c#L422).

Is this an intentional change?

**Comment by DavidWooten** [comment]
When you load an object without a sensitive area, it can’t be used for authorization so the authPolicy size is moot.

 

From: Brian Granaghan ***@***.*** 
Sent: Tuesday, June 7, 2022 6:36 PM
To: microsoft/ms-tpm-20-ref
Cc: Subscribed
Subject: [microsoft/ms-tpm-20-ref] TPM2_LoadExternal does not validate authPolicy size if private area is not loaded. (Issue #71)

 

TPM2_LoadExternal <https://github.com/microsoft/ms-tpm-20-ref/blob/b8e599267381badbe0571f8ace55b28a5f16457c/TPMCmd/tpm/src/command/Object/LoadExternal.c#L86>  explicitly checked the authPolicy size in 1.16 <https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.16-code.pdf>  and this was dropped in 1.38 <https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38-code.pdf> . I have not been able to find an errata relating to it.
PublicAttributesValidation <https://github.com/microsoft/ms-tpm-20-ref/blob/b8e599267381badbe0571f8ace55b28a5f16457c/TPMCmd/tpm/src/command/Object/Object_spt.c#L618>  checks this, but is only called is the private area is loaded here <https://github.com/microsoft/ms-tpm-20-ref/blob/b8e599267381badbe0571f8ace55b28a5f16457c/TPMCmd/tpm/src/subsystem/Object.c#L422> .

Is this an intentional change?
